@startuml TODOAPP
actor ユーザー

left to right direction
' 認証関連の操作
rectangle "認証" {
    ユーザー -- (新規登録する)
    ユーザー -- (ログインする)
    ユーザー -- (ログアウトする)
}

' タスク関連の操作
rectangle "タスク管理" {
    ユーザー -- (タスクを作成する)
    ユーザー -- (タスク一覧を取得する)
    ユーザー -- (タスクの詳細を取得する)
    ユーザー -- (タスクを更新する)
    ユーザー -- (タスクを削除する)
}
@enduml
